# Generated by Django 5.2.5 on 2025-11-04 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcq", "0019_merge_explanations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminDebugEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Browser session key to correlate frontend events.",
                        max_length=64,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Event type identifier (e.g., frontend_click, api_response).",
                        max_length=64,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("backend", "Backend"),
                            ("api", "API Gateway"),
                            ("system", "System"),
                        ],
                        default="backend",
                        help_text="Origin of the event.",
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        help_text="Severity level for quick filtering.",
                        max_length=16,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Human-readable message describing the event."
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured metadata for the event.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with the event, if available.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_debug_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Debug Event",
                "verbose_name_plural": "Admin Debug Events",
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["-occurred_at"], name="mcq_adminde_occurre_08d5ed_idx"
                    ),
                    models.Index(
                        fields=["event_type", "-occurred_at"],
                        name="mcq_adminde_event_t_7238fc_idx",
                    ),
                    models.Index(
                        fields=["source", "severity"],
                        name="mcq_adminde_source_14919f_idx",
                    ),
                ],
            },
        ),
    ]
