# Generated by Django 5.2.5 on 2025-11-04 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcq", "0020_admindebugevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIEditJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("question_edit", "Question Edit"),
                            ("options_edit", "Options Edit"),
                            ("explanation_edit", "Explanation Edit"),
                            ("explanation_regenerate", "Explanation Regenerate"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mcq",
                    models.ForeignKey(
                        help_text="The MCQ this AI job operates on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_jobs",
                        to="mcq.mcq",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the job.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Edit Job",
                "verbose_name_plural": "AI Edit Jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job_type", "-created_at"],
                        name="mcq_aieditj_job_typ_9b3379_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="mcq_aieditj_status_5393c5_idx",
                    ),
                ],
            },
        ),
    ]
